const shopifyTypes = {
    FETCH_ALL_PRODUCTS: 'FETCH_ALL_PRODUCTS',
    CREATE_CHECKOUT: 'CREATE_CHECKOUT',
    FETCH_PRODUCT_ID: 'FETCH_PRODUCT_ID',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART'
}

export default shopifyTypes
